#############################################################################
# Makefile for building: qchuck
# Generated by qmake (2.01a) (Qt 4.8.0) on: Mon May 28 16:35:54 2012
# Project:  qchuck.pro
# Template: app
# Command: /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile qchuck.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ -I. -I/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtCore.framework/Versions/4/Headers -I/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/lib/QtNetwork.framework/Versions/4/Headers -I/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtNetwork -I/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/include -Iqjson/include -I. -F/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/lib -F/Users/ynonperek/Courses/QtCollege/articles/chuck/qchuck/qjson/lib/ -framework qjson -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		chucknorrisapi.cpp \
		joke.cpp \
		chuckapp.cpp moc_chucknorrisapi.cpp \
		moc_chuckapp.cpp
OBJECTS       = main.o \
		chucknorrisapi.o \
		joke.o \
		chuckapp.o \
		moc_chucknorrisapi.o \
		moc_chuckapp.o
DIST          = /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		qchuck.pro
QMAKE_TARGET  = qchuck
DESTDIR       = 
TARGET        = qchuck

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qchuck.pro  /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++/qmake.conf /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		/Users/ynonperek/Courses/QtCollege/articles/chuck/qchuck/qjson/lib/qjson.framework/qjson.prl
	$(QMAKE) -spec /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile qchuck.pro
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
/Users/ynonperek/Courses/QtCollege/articles/chuck/qchuck/qjson/lib/qjson.framework/qjson.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile qchuck.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qchuck1.0.0 || $(MKDIR) .tmp/qchuck1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qchuck1.0.0/ && $(COPY_FILE) --parents chucknorrisapi.h joke.h chuckapp.h .tmp/qchuck1.0.0/ && $(COPY_FILE) --parents main.cpp chucknorrisapi.cpp joke.cpp chuckapp.cpp .tmp/qchuck1.0.0/ && (cd `dirname .tmp/qchuck1.0.0` && $(TAR) qchuck1.0.0.tar qchuck1.0.0 && $(COMPRESS) qchuck1.0.0.tar) && $(MOVE) `dirname .tmp/qchuck1.0.0`/qchuck1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qchuck1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_chucknorrisapi.cpp moc_chuckapp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chucknorrisapi.cpp moc_chuckapp.cpp
moc_chucknorrisapi.cpp: chucknorrisapi.h
	/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ chucknorrisapi.h -o moc_chucknorrisapi.cpp

moc_chuckapp.cpp: chucknorrisapi.h \
		joke.h \
		chuckapp.h
	/Users/ynonperek/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ chuckapp.h -o moc_chuckapp.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp chuckapp.h \
		chucknorrisapi.h \
		joke.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

chucknorrisapi.o: chucknorrisapi.cpp chucknorrisapi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chucknorrisapi.o chucknorrisapi.cpp

joke.o: joke.cpp joke.h \
		qjson/include/QJson/Parser \
		qjson/src/parser.h \
		qjson/src/qjson_export.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o joke.o joke.cpp

chuckapp.o: chuckapp.cpp chuckapp.h \
		chucknorrisapi.h \
		joke.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chuckapp.o chuckapp.cpp

moc_chucknorrisapi.o: moc_chucknorrisapi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chucknorrisapi.o moc_chucknorrisapi.cpp

moc_chuckapp.o: moc_chuckapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chuckapp.o moc_chuckapp.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

